
import React, { useState } from 'react';
import { ModuleComponentProps, DirectDebitMandate } from './types';
import { mockDirectDebitMandates, mockProAccountDetails } from './data';
import { DocumentPlusIcon } from '../../constants/icons';

// Simulate company details that would typically come from settings or context
const COMPANY_CREDITOR_NAME = mockProAccountDetails.accountName; 
const COMPANY_CREDITOR_ID = "FR00ZZZ123456"; // Example SEPA Creditor Identifier

const ProAccountCreateMandatePage: React.FC<ModuleComponentProps> = ({ onSubNavigate }) => {
  const [formData, setFormData] = useState({
    debtorName: '',
    debtorIban: '',
    debtorCountry: 'France', // Default
    mandateDisplayName: '', 
    mandateType: 'CORE' as 'CORE' | 'B2B',
    frequency: 'Mensuel' as 'Ponctuel' | 'Mensuel' | 'Trimestriel' | 'Annuel', // UPDATED: field name and type
    notes: '', 
  });
  const [formError, setFormError] = useState<string | null>(null);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    setFormError(null);
  };

  const validateIBAN = (iban: string): boolean => {
    const ibanPattern = /^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$/; // Basic IBAN pattern
    return ibanPattern.test(iban.replace(/\s/g, '').toUpperCase());
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!formData.debtorName.trim()) {
      setFormError('Le nom du débiteur est requis.');
      return;
    }
    if (!validateIBAN(formData.debtorIban)) {
      setFormError('Veuillez saisir un IBAN valide pour le débiteur.');
      return;
    }
    if (!formData.mandateDisplayName.trim()) {
      setFormError('Veuillez saisir un nom pour ce mandat (ex: Abonnement XYZ).');
      return;
    }

    const newMandate: DirectDebitMandate = {
      id: `ddm-${Date.now()}`,
      creditorName: COMPANY_CREDITOR_NAME,
      creditorId: COMPANY_CREDITOR_ID,
      mandateReference: `UMR-${formData.debtorName.substring(0,3).toUpperCase()}${Date.now().toString().slice(-4)}`, // Example UMR
      debtorName: formData.debtorName,
      debtorIban: formData.debtorIban.replace(/\s/g, '').toUpperCase(),
      debtorCountry: formData.debtorCountry,
      mandateLanguage: 'Français', // Default
      mandateDisplayName: formData.mandateDisplayName,
      status: 'Généré', 
      creationDate: new Date().toISOString().split('T')[0],
      mandateType: formData.mandateType,
      frequency: formData.frequency, // Correctly assignable now
      // pdfLink: would be generated by backend and stored
    };

    console.log('Creating New Mandate:', newMandate);
    mockDirectDebitMandates.push(newMandate); 
    alert(`Mandat pour ${formData.debtorName} créé avec la RUM ${newMandate.mandateReference}.`);
    
    if (onSubNavigate) {
      onSubNavigate('comptes_pro_prelevements'); 
    }
  };

  const handleCancel = () => {
    if (onSubNavigate) {
      onSubNavigate('comptes_pro_prelevements');
    }
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 bg-white shadow-xl rounded-lg max-w-2xl mx-auto">
      <div className="flex items-center mb-6">
        <DocumentPlusIcon className="w-8 h-8 text-theme-primary-500 mr-3" />
        <h2 className="text-2xl font-semibold text-theme-text">Créer un Mandat de Prélèvement SEPA</h2>
      </div>
      
      <form onSubmit={handleSubmit} className="space-y-6">
        <fieldset className="border border-gray-300 p-4 rounded-md">
            <legend className="text-sm font-medium text-theme-text px-2">Informations du Débiteur</legend>
            <div className="space-y-4 mt-2">
                <div>
                    <label htmlFor="debtorName" className="block text-xs font-medium text-gray-700 mb-1">
                        Nom complet ou Raison sociale <span className="text-red-500">*</span>
                    </label>
                    <input type="text" name="debtorName" id="debtorName" value={formData.debtorName} onChange={handleInputChange} required className="w-full p-2.5 border border-gray-300 rounded-md shadow-sm text-sm focus:ring-theme-primary-500 focus:border-theme-primary-500"/>
                </div>
                <div>
                    <label htmlFor="debtorIban" className="block text-xs font-medium text-gray-700 mb-1">
                        IBAN du débiteur <span className="text-red-500">*</span>
                    </label>
                    <input type="text" name="debtorIban" id="debtorIban" value={formData.debtorIban} onChange={handleInputChange} placeholder="FRXX XXXX XXXX XXXX XXXX XXXX X" required className="w-full p-2.5 border border-gray-300 rounded-md shadow-sm text-sm focus:ring-theme-primary-500 focus:border-theme-primary-500"/>
                </div>
            </div>
        </fieldset>

        <fieldset className="border border-gray-300 p-4 rounded-md">
            <legend className="text-sm font-medium text-theme-text px-2">Détails du Mandat</legend>
            <div className="space-y-4 mt-2">
                <div>
                    <label htmlFor="mandateDisplayName" className="block text-xs font-medium text-gray-700 mb-1">
                        Nom du mandat (pour votre référence) <span className="text-red-500">*</span>
                    </label>
                    <input type="text" name="mandateDisplayName" id="mandateDisplayName" value={formData.mandateDisplayName} onChange={handleInputChange} placeholder="Ex: Abonnement Services XYZ" required className="w-full p-2.5 border border-gray-300 rounded-md shadow-sm text-sm focus:ring-theme-primary-500 focus:border-theme-primary-500"/>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label htmlFor="mandateType" className="block text-xs font-medium text-gray-700 mb-1">Type de mandat</label>
                        <select name="mandateType" id="mandateType" value={formData.mandateType} onChange={handleInputChange} className="w-full p-2.5 border border-gray-300 rounded-md shadow-sm text-sm focus:ring-theme-primary-500 focus:border-theme-primary-500">
                            <option value="CORE">CORE (Particuliers et Entreprises)</option>
                            <option value="B2B">B2B (Entreprises uniquement)</option>
                        </select>
                    </div>
                    <div>
                        <label htmlFor="frequency" className="block text-xs font-medium text-gray-700 mb-1">Fréquence des paiements</label>
                         <select name="frequency" id="frequency" value={formData.frequency} onChange={handleInputChange} className="w-full p-2.5 border border-gray-300 rounded-md shadow-sm text-sm focus:ring-theme-primary-500 focus:border-theme-primary-500">
                            <option value="Ponctuel">Ponctuel (Un seul paiement)</option>
                            <option value="Mensuel">Mensuel</option>
                            <option value="Trimestriel">Trimestriel</option>
                            <option value="Annuel">Annuel</option>
                        </select>
                    </div>
                </div>
                 <div>
                    <label htmlFor="notes" className="block text-xs font-medium text-gray-700 mb-1">
                        Notes (optionnel)
                    </label>
                    <textarea name="notes" id="notes" value={formData.notes} onChange={handleInputChange} rows={2} placeholder="Informations complémentaires..." className="w-full p-2.5 border border-gray-300 rounded-md shadow-sm text-sm focus:ring-theme-primary-500 focus:border-theme-primary-500 resize-none"/>
                </div>
            </div>
        </fieldset>
        
        {formError && (
          <div role="alert" className="p-3 bg-red-50 text-red-700 border border-red-200 rounded-md text-sm">
            {formError}
          </div>
        )}

        <div className="pt-2 text-xs text-gray-500">
            <p><strong>Note :</strong> La création de ce mandat est une simulation. Dans un système réel, des étapes de signature électronique par le débiteur et de validation bancaire seraient nécessaires.</p>
        </div>

        <div className="flex flex-col sm:flex-row justify-end items-center gap-3 pt-4 border-t border-gray-200">
          <p className="text-xs text-gray-500 mr-auto sm:mr-4">Les champs marqués d'une <span className="text-red-500">*</span> sont obligatoires.</p>
          <button
            type="button"
            onClick={handleCancel}
            className="w-full sm:w-auto px-6 py-2.5 text-sm font-medium text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 border border-gray-300 transition-colors"
          >
            Annuler
          </button>
          <button
            type="submit"
            className="w-full sm:w-auto px-6 py-2.5 text-sm font-medium text-white bg-theme-primary-500 rounded-md hover:bg-theme-primary-600 transition-colors flex items-center justify-center focus:ring-2 focus:ring-offset-2 focus:ring-theme-primary-400"
          >
            <DocumentPlusIcon className="w-5 h-5 mr-2" />
            Générer le mandat
          </button>
        </div>
      </form>
    </div>
  );
};

export default ProAccountCreateMandatePage;
